//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.03 at 12:23:46 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(
		namespace = "uri:oozie:workflow:0.5", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package etl.flow.oozie.wf;
