//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.03 at 12:23:46 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
		xmlns = { 
				@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi"),
				@javax.xml.bind.annotation.XmlNs(namespaceURI = "uri:oozie:shell-action:0.3", prefix = "shell"),
				@javax.xml.bind.annotation.XmlNs(namespaceURI = "uri:oozie:ssh-action:0.2", prefix = "ssh"),
				@javax.xml.bind.annotation.XmlNs(namespaceURI = "uri:oozie:workflow:0.5", prefix = ""),
				
		}
	)
package etl.flow.oozie.wf;

