//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.21 at 03:56:46 PM PDT 
//


package etl.flow.oozie.coord;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for INPUTLOGIC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INPUTLOGIC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="and" type="{uri:oozie:coordinator:0.5}LOGICALAND" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="or" type="{uri:oozie:coordinator:0.5}LOGICALOR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="combine" type="{uri:oozie:coordinator:0.5}COMBINE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="data-in" type="{uri:oozie:coordinator:0.5}LOGICALDATAIN" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INPUTLOGIC", propOrder = {
    "andOrOrOrCombine"
})
public class INPUTLOGIC {

    @XmlElements({
        @XmlElement(name = "and", type = LOGICALAND.class),
        @XmlElement(name = "or", type = LOGICALOR.class),
        @XmlElement(name = "combine", type = COMBINE.class),
        @XmlElement(name = "data-in", type = LOGICALDATAIN.class)
    })
    protected List<Object> andOrOrOrCombine;

    /**
     * Gets the value of the andOrOrOrCombine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the andOrOrOrCombine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAndOrOrOrCombine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LOGICALAND }
     * {@link LOGICALOR }
     * {@link COMBINE }
     * {@link LOGICALDATAIN }
     * 
     * 
     */
    public List<Object> getAndOrOrOrCombine() {
        if (andOrOrOrCombine == null) {
            andOrOrOrCombine = new ArrayList<Object>();
        }
        return this.andOrOrOrCombine;
    }

}
