//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.21 at 03:56:46 PM PDT 
//


package etl.flow.oozie.coord;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LOGICALOR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LOGICALOR">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="and" type="{uri:oozie:coordinator:0.5}LOGICALAND" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="or" type="{uri:oozie:coordinator:0.5}LOGICALOR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="data-in" type="{uri:oozie:coordinator:0.5}LOGICALDATAIN" maxOccurs="unbounded"/>
 *         &lt;element name="combine" type="{uri:oozie:coordinator:0.5}COMBINE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wait" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LOGICALOR", propOrder = {
    "andOrOrOrDataIn"
})
public class LOGICALOR {

    @XmlElements({
        @XmlElement(name = "and", type = LOGICALAND.class),
        @XmlElement(name = "or", type = LOGICALOR.class),
        @XmlElement(name = "data-in", type = LOGICALDATAIN.class),
        @XmlElement(name = "combine", type = COMBINE.class)
    })
    protected List<Object> andOrOrOrDataIn;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "min")
    protected String min;
    @XmlAttribute(name = "wait")
    protected String wait;

    /**
     * Gets the value of the andOrOrOrDataIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the andOrOrOrDataIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAndOrOrOrDataIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LOGICALAND }
     * {@link LOGICALOR }
     * {@link LOGICALDATAIN }
     * {@link COMBINE }
     * 
     * 
     */
    public List<Object> getAndOrOrOrDataIn() {
        if (andOrOrOrDataIn == null) {
            andOrOrOrDataIn = new ArrayList<Object>();
        }
        return this.andOrOrOrDataIn;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMin(String value) {
        this.min = value;
    }

    /**
     * Gets the value of the wait property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWait() {
        return wait;
    }

    /**
     * Sets the value of the wait property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWait(String value) {
        this.wait = value;
    }

}
