//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.18 at 04:44:40 PM PDT 
//


package nokia.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.3gpp.org/ftp/specs/latest/rel-5/32_series/32401-540.zip#measCollec}fileSender"/>
 *         &lt;element ref="{http://www.3gpp.org/ftp/specs/latest/rel-5/32_series/32401-540.zip#measCollec}measCollec"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fileFormatVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vendorName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dnPrefix" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileSender",
    "measCollec"
})
@XmlRootElement(name = "fileHeader")
public class FileHeader {

    @XmlElement(required = true)
    protected FileSender fileSender;
    @XmlElement(required = true)
    protected MeasCollec measCollec;
    @XmlAttribute(name = "fileFormatVersion", required = true)
    protected String fileFormatVersion;
    @XmlAttribute(name = "vendorName", required = true)
    protected String vendorName;
    @XmlAttribute(name = "dnPrefix", required = true)
    protected String dnPrefix;

    /**
     * Gets the value of the fileSender property.
     * 
     * @return
     *     possible object is
     *     {@link FileSender }
     *     
     */
    public FileSender getFileSender() {
        return fileSender;
    }

    /**
     * Sets the value of the fileSender property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileSender }
     *     
     */
    public void setFileSender(FileSender value) {
        this.fileSender = value;
    }

    /**
     * Gets the value of the measCollec property.
     * 
     * @return
     *     possible object is
     *     {@link MeasCollec }
     *     
     */
    public MeasCollec getMeasCollec() {
        return measCollec;
    }

    /**
     * Sets the value of the measCollec property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasCollec }
     *     
     */
    public void setMeasCollec(MeasCollec value) {
        this.measCollec = value;
    }

    /**
     * Gets the value of the fileFormatVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileFormatVersion() {
        return fileFormatVersion;
    }

    /**
     * Sets the value of the fileFormatVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileFormatVersion(String value) {
        this.fileFormatVersion = value;
    }

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the dnPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnPrefix() {
        return dnPrefix;
    }

    /**
     * Sets the value of the dnPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnPrefix(String value) {
        this.dnPrefix = value;
    }

}
