//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.18 at 04:44:40 PM PDT 
//


package nokia.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.3gpp.org/ftp/specs/latest/rel-5/32_series/32401-540.zip#measCollec}measCollec"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "measCollec"
})
@XmlRootElement(name = "fileFooter")
public class FileFooter {

    @XmlElement(required = true)
    protected MeasCollec measCollec;

    /**
     * Gets the value of the measCollec property.
     * 
     * @return
     *     possible object is
     *     {@link MeasCollec }
     *     
     */
    public MeasCollec getMeasCollec() {
        return measCollec;
    }

    /**
     * Sets the value of the measCollec property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasCollec }
     *     
     */
    public void setMeasCollec(MeasCollec value) {
        this.measCollec = value;
    }

}
