//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.18 at 04:44:40 PM PDT 
//


package nokia.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.3gpp.org/ftp/specs/latest/rel-5/32_series/32401-540.zip#measCollec}fileHeader"/>
 *         &lt;element ref="{http://www.3gpp.org/ftp/specs/latest/rel-5/32_series/32401-540.zip#measCollec}measData"/>
 *         &lt;element ref="{http://www.3gpp.org/ftp/specs/latest/rel-5/32_series/32401-540.zip#measCollec}fileFooter"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileHeader",
    "measData",
    "fileFooter"
})
@XmlRootElement(name = "measCollecFile")
public class MeasCollecFile {

    @XmlElement(required = true)
    protected FileHeader fileHeader;
    @XmlElement(required = true)
    protected MeasData measData;
    @XmlElement(required = true)
    protected FileFooter fileFooter;

    /**
     * Gets the value of the fileHeader property.
     * 
     * @return
     *     possible object is
     *     {@link FileHeader }
     *     
     */
    public FileHeader getFileHeader() {
        return fileHeader;
    }

    /**
     * Sets the value of the fileHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileHeader }
     *     
     */
    public void setFileHeader(FileHeader value) {
        this.fileHeader = value;
    }

    /**
     * Gets the value of the measData property.
     * 
     * @return
     *     possible object is
     *     {@link MeasData }
     *     
     */
    public MeasData getMeasData() {
        return measData;
    }

    /**
     * Sets the value of the measData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasData }
     *     
     */
    public void setMeasData(MeasData value) {
        this.measData = value;
    }

    /**
     * Gets the value of the fileFooter property.
     * 
     * @return
     *     possible object is
     *     {@link FileFooter }
     *     
     */
    public FileFooter getFileFooter() {
        return fileFooter;
    }

    /**
     * Sets the value of the fileFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileFooter }
     *     
     */
    public void setFileFooter(FileFooter value) {
        this.fileFooter = value;
    }

}
