//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.18 at 04:44:40 PM PDT 
//


package nokia.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nokia.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nokia.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MeasData }
     * 
     */
    public MeasData createMeasData() {
        return new MeasData();
    }

    /**
     * Create an instance of {@link ManagedElement }
     * 
     */
    public ManagedElement createManagedElement() {
        return new ManagedElement();
    }

    /**
     * Create an instance of {@link MeasInfo }
     * 
     */
    public MeasInfo createMeasInfo() {
        return new MeasInfo();
    }

    /**
     * Create an instance of {@link GranPeriod }
     * 
     */
    public GranPeriod createGranPeriod() {
        return new GranPeriod();
    }

    /**
     * Create an instance of {@link MeasType }
     * 
     */
    public MeasType createMeasType() {
        return new MeasType();
    }

    /**
     * Create an instance of {@link MeasValue }
     * 
     */
    public MeasValue createMeasValue() {
        return new MeasValue();
    }

    /**
     * Create an instance of {@link R }
     * 
     */
    public R createR() {
        return new R();
    }

    /**
     * Create an instance of {@link MeasCollecFile }
     * 
     */
    public MeasCollecFile createMeasCollecFile() {
        return new MeasCollecFile();
    }

    /**
     * Create an instance of {@link FileHeader }
     * 
     */
    public FileHeader createFileHeader() {
        return new FileHeader();
    }

    /**
     * Create an instance of {@link FileSender }
     * 
     */
    public FileSender createFileSender() {
        return new FileSender();
    }

    /**
     * Create an instance of {@link MeasCollec }
     * 
     */
    public MeasCollec createMeasCollec() {
        return new MeasCollec();
    }

    /**
     * Create an instance of {@link FileFooter }
     * 
     */
    public FileFooter createFileFooter() {
        return new FileFooter();
    }

}
