//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.18 at 04:44:40 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.3gpp.org/ftp/specs/latest/rel-5/32_series/32401-540.zip#measCollec", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nokia.xml;
