drop schema SMSC cascade;
CREATE SCHEMA IF NOT EXISTS SMSC;

CREATE TABLE IF NOT EXISTS  SMSC.MMDS_SMS_Gen_Op(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
Billing_record_commit  numeric(15,3),				
Billing_record_failed  numeric(15,3),				
Msg_Status_Table_Size  numeric(15,3),				
Dlvry_Ack_created  numeric(15,3),				
Msg_Overload_Rjct  numeric(15,3),				
Msg_Status_Num_Inserts  numeric(15,3),				
Msg_Status_Num_Deletes  numeric(15,3),				
Green_Zone_Restrict  numeric(15,3),				
Signature_Success  numeric(15,3),				
Signature_Failure  numeric(15,3),				
Banner_Success  numeric(15,3),				
Banner_Failure  numeric(15,3),				
DelAckSuppress  numeric(15,3),				
LongMsgRelayTruncated  numeric(15,3),				
SCPR_Rcvd  numeric(15,3),				
Imsst_Received  numeric(15,3),				
Imsst_Success  numeric(15,3),				
InternalMsg_subType1  numeric(15,3),				
FDA_to_MDA  numeric(15,3),				
MO_Escalate_after_SS7  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.MMDS_Msg_Delvrd_Hist(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
Total  numeric(15,3),			
Counter_1  numeric(15,3),			
Counter_2  numeric(15,3),			
Counter_3  numeric(15,3),			
Counter_4  numeric(15,3),			
Counter_5  numeric(15,3),			
Counter_6  numeric(15,3),			
Counter_7  numeric(15,3),			
Counter_8  numeric(15,3),			
Counter_9  numeric(15,3),			
Aux_11  numeric(15,3),			
Aux_12  numeric(15,3),			
Aux_13  numeric(15,3),			
Aux_14  numeric(15,3),			
Aux_15  numeric(15,3),			
Aux_16  numeric(15,3),			
Aux_17  numeric(15,3),			
Aux_18  numeric(15,3),			
Aux_19  numeric(15,3),			
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.MMDS_IS41_Stats(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
SMSRqst_Invoke  numeric(15,3),			
SMSRqst_RR_Success  numeric(15,3),			
SMSRqst_RR_Denied  numeric(15,3),			
SMSRqst_RR_Delayed  numeric(15,3),			
SMSRqst_RR_Failure  numeric(15,3),			
SMSRqst_RR_OtherErr  numeric(15,3),			
SMSRqst_NS_NotSent  numeric(15,3),			
SMSRqst_ER_Unkwn_MIN  numeric(15,3),			
SMSRqst_ER_ErrorRtrn  numeric(15,3),			
SMSDPP_Invoke  numeric(15,3),			
SMSDPP_Success  numeric(15,3),			
SMSDPP_RR  numeric(15,3),			
SMSDPP_Not_Sent  numeric(15,3),			
SMSDPP_Error_Returned  numeric(15,3),			
SMSNotify_Invoke  numeric(15,3),			
To_SMSC_Success  numeric(15,3),			
To_SMSC_Dpp_Attempts  numeric(15,3),			
InfoDir_Invoke  numeric(15,3),			
MsgDir_Invoke  numeric(15,3),			
SMSDPP_Cell_Success  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.MMDS_GSM_IMS_Stats(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
SRI_Send_Total  numeric(15,3),			
SRI_Success  numeric(15,3),			
InfoSCReceived_Total  numeric(15,3),			
MT_FSM_Send_Total  numeric(15,3),			
MT_FSM_Success  numeric(15,3),			
RptSM_Send_Total  numeric(15,3),			
RptSM_Success  numeric(15,3),			
UDR_Invoke  numeric(15,3),			
UDR_Not_Sent  numeric(15,3),			
UDR_Error_Returned  numeric(15,3),			
SIP_Invoke  numeric(15,3),			
SIP_Not_Sent  numeric(15,3),			
SIP_Error_Returned  numeric(15,3),			
SNR_Subscribe_sent  numeric(15,3),			
SNR_Unsubscribe_sent  numeric(15,3),			
SNR_failed  numeric(15,3),			
SMS_Ack_ignored  numeric(15,3),			
SS7_Fallback_Success  numeric(15,3),			
SIP_GSM_Deliver  numeric(15,3),			
SIP_GSM_StatusReport  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.MMDS_Data_Stats(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
Free_List_size  numeric(15,3),			
MIN_Index_size  numeric(15,3),			
Util_TBR  numeric(15,3),			
DlvryInit_New  numeric(15,3),			
DlvryInit_Notify  numeric(15,3),			
DlvryInit_TBR  numeric(15,3),			
DlvryInit_Sync  numeric(15,3),			
DlvryInit_N_Discard  numeric(15,3),			
DlvryInit_unkwn  numeric(15,3),			
SS7_New_Msg_Timeout  numeric(15,3),			
SS7_Extend_Given  numeric(15,3),			
SS7_Hung_Call_Detect  numeric(15,3),			
SS7  numeric(15,3),			
SS7_First_Attempts  numeric(15,3),			
SS7_Immediate  numeric(15,3),			
PreSplitMinDPP_Atmpt  numeric(15,3),			
PreSplitMinDPP_Err  numeric(15,3),			
SS7_Trans_Not_Avail  numeric(15,3),			
CellArrival  numeric(15,3),			
Escalate_after_SS7  numeric(15,3)
);


CREATE TABLE IF NOT EXISTS  SMSC.MMDS_MSGQ_Ins_and_Read(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
I_Attempt  numeric(15,3),			
I_Success  numeric(15,3),			
I_E_Dup_Key  numeric(15,3),			
I_E_Limit_Reached  numeric(15,3),			
I_E_Internal_Err  numeric(15,3),			
I_E_Time_Out  numeric(15,3),			
I_Other_Fail  numeric(15,3),			
R_Attempt  numeric(15,3),			
R_Success  numeric(15,3),			
R_E_Tuple_Not_Found  numeric(15,3),			
R_E_Internal_Err  numeric(15,3),			
R_E_Time_Out  numeric(15,3),			
R_Other_Fail  numeric(15,3),			
Aux_14  numeric(15,3),			
Aux_15  numeric(15,3),			
Alt_IF_Used  numeric(15,3),			
Alt_IF_CDMA  numeric(15,3),			
Alt_IF_GSM  numeric(15,3),			
Alt_IF_Rmvd  numeric(15,3),			
Alt_IF_Churn  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.MMDS_MSGQ_Update_Del(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
U_Attempt  numeric(15,3),			
U_Success  numeric(15,3),			
U_E_Tuple_Not_Found  numeric(15,3),			
U_E_Internal_Err  numeric(15,3),			
U_E_Time_Out  numeric(15,3),			
U_Other_Fail  numeric(15,3),			
D_Attempt  numeric(15,3),			
D_Success  numeric(15,3),			
D_E_Tuple_Not_Found  numeric(15,3),			
D_E_Internal_Err  numeric(15,3),			
D_E_Time_Out  numeric(15,3),			
D_Other_Fail  numeric(15,3),			
Aux_13  numeric(15,3),			
Aux_14  numeric(15,3),			
Aux_15  numeric(15,3),			
Aux_16  numeric(15,3),			
Aux_17  numeric(15,3),			
Aux_18  numeric(15,3),			
Aux_19  numeric(15,3),			
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.MMDS_SMS_Prepaid_Status(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
PPD_DebitRequest_Success  numeric(15,3),			
PPD_DebitRequest_Failure  numeric(15,3),			
PPD_QueryBalance_Success  numeric(15,3),			
PPD_QueryBalance_Failure  numeric(15,3),			
PPD_CreditRequest_Success  numeric(15,3),			
PPD_CreditRequest_Failure  numeric(15,3),			
PPD_Free_Messages  numeric(15,3),			
RDB_Writes_Sent  numeric(15,3),			
RDB_Write_Success  numeric(15,3),			
RDB_Write_Errors  numeric(15,3),			
RDB_Write_Failures  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS SMSC.MMDS_Prepaid_Failures(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
PPD_AllocationLost  numeric(15,3),			
PPD_ServerBusy  numeric(15,3),			
PPD_ProtocolViolations  numeric(15,3),			
PPD_InvalidMissParameter  numeric(15,3),			
PPD_InvalidSubscrDetails  numeric(15,3),			
PPD_ECommerceDisabled  numeric(15,3),			
PPD_InvalidMerchantId  numeric(15,3),			
PPD_SubscriberActivityBarred  numeric(15,3),			
PPD_CallsInProgress  numeric(15,3),			
PPD_WrongTypeMissBalance  numeric(15,3),			
PPD_UnsubscribedService  numeric(15,3),			
PPD_InsufficientFunds  numeric(15,3),			
PPD_UnknownError  numeric(15,3),			
PPD_InternalError  numeric(15,3),			
UC_TOD_Denial  numeric(15,3),			
UC_Other_Denial  numeric(15,3)
); 	

CREATE TABLE IF NOT EXISTS SMSC.MMDS_PPD_Diam_Failures(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
PPD_RC_3004  numeric(15,3),			
PPD_RC_4010  numeric(15,3),			
PPD_RC_4012  numeric(15,3),			
PPD_RC_5003  numeric(15,3),			
PPD_RC_5004  numeric(15,3),			
PPD_RC_5005  numeric(15,3),			
PPD_RC_5012  numeric(15,3),			
PPD_RC_5030  numeric(15,3),			
PPD_RC_5031  numeric(15,3),			
Aux_10  numeric(15,3),			
Aux_11  numeric(15,3),			
Aux_12  numeric(15,3),			
Aux_13  numeric(15,3),			
Aux_14  numeric(15,3),			
Aux_15  numeric(15,3),			
PPD_InternalError  numeric(15,3),			
PPD_NoResponse  numeric(15,3),			
PPD_ProtocolError  numeric(15,3),			
PPD_PermanentFailure  numeric(15,3),			
PPD_UnknownError  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS SMSC.MMDS_MME_Stats(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
SRR_Send_Total  numeric(15,3),			
SRR_Success  numeric(15,3),			
TFR_Send_Total  numeric(15,3),			
TFR_Success  numeric(15,3),			
RDR_Send_Total  numeric(15,3),			
RDR_Success  numeric(15,3),			
DelivRep_Recvd  numeric(15,3),			
Aux_8  numeric(15,3),			
Aux_9  numeric(15,3),			
Aux_10  numeric(15,3),			
Aux_11  numeric(15,3),			
Aux_12  numeric(15,3),			
Aux_13  numeric(15,3),			
Aux_14  numeric(15,3),			
Aux_15  numeric(15,3),			
Aux_16  numeric(15,3),			
Aux_17  numeric(15,3),			
Aux_18  numeric(15,3),			
Aux_19  numeric(15,3),			
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_MO_Status_DPP(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
MO_Msg_Arrival  numeric(15,3),
MO_CDMA_Received  numeric(15,3),
MO_TDMA_Received  numeric(15,3),
MO_RR_Sent  numeric(15,3),
MO_RR_Not_Sent  numeric(15,3),
MO_RE_Sent  numeric(15,3),
MO_RE_Not_Sent  numeric(15,3),
SMSNotify_Received  numeric(15,3),
SMSNotify_RR_Success  numeric(15,3),
SMSNotify_RR_NotSent  numeric(15,3),
NotifyWithMDNRecvd  numeric(15,3),
MO_CDMA_EMS_Rcvd  numeric(15,3),
SMSNotify_RE_Success  numeric(15,3),
SMSNotify_RE_NotSent  numeric(15,3),
MO_Read_Ack_Rcvd  numeric(15,3),
MO_From_Other_SMSC  numeric(15,3),
Gen_Auto_Reply  numeric(15,3),
MO_to_SMPP  numeric(15,3),
MO_to_MT  numeric(15,3),
MO_FDA_to_MDA  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_GSM_Received(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
MO_FSM_Received_Totl  numeric(15,3),
MO_FSM_Received_v2  numeric(15,3),
MO_FSM_Received_v3  numeric(15,3),
MO_FSM_Submit_Rcvd  numeric(15,3),
MO_FSM_Command_Rcvd  numeric(15,3),
MO_FSM_RS_Success  numeric(15,3),
MO_FSM_ES_Success  numeric(15,3),
ASC_Received_Total  numeric(15,3),
ASC_Received_v2  numeric(15,3),
ASC_Received_v3  numeric(15,3),
ASC_RS_Success  numeric(15,3),
ASC_ES_Success  numeric(15,3),
SRI_for_SM_Received  numeric(15,3),
SRI_for_SM_Resp_Success  numeric(15,3),
SRI_for_SM_Resp_Error  numeric(15,3),
MT_FSM_Received  numeric(15,3),
MT_FSM_Resp_Success  numeric(15,3),
MT_FSM_Resp_Error  numeric(15,3),
SMS_Deliv_Received  numeric(15,3),
SMS_Status_Rep_Received  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_Validate_Msg_Status(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
IntervalShortMessage  numeric(15,3),			
MessagesToSmpp  numeric(15,3),			
MessagesToMsgMgr  numeric(15,3),			
BliArrival  numeric(15,3),			
InvalidServiceType  numeric(15,3),			
InvalidSourceDN  numeric(15,3),			
InvalidDestinationDN  numeric(15,3),			
InvalidCOS  numeric(15,3),			
OriginationDenied  numeric(15,3),			
TerminationDenied  numeric(15,3),			
RoutingFailed  numeric(15,3),			
SystemError  numeric(15,3),			
ClntNotInService  numeric(15,3),			
Val_Sends  numeric(15,3),			
Val_XP_Sends  numeric(15,3),			
DeliveryReceipts  numeric(15,3),			
SMSC_Loop_Detected  numeric(15,3),			
CarbonCopies  numeric(15,3),			
Forwards  numeric(15,3),			
InternalMsg  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_Filter_List_Status(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
WHTListSearches  numeric(15,3),			
WHTListRejects  numeric(15,3),			
GlobalWHTListAccepts  numeric(15,3),			
BLKListSearches  numeric(15,3),			
BLKListRejects  numeric(15,3),			
BlockedByRating  numeric(15,3),			
DelayedResponse  numeric(15,3),			
WrongResponse  numeric(15,3),			
EmptyMessage  numeric(15,3),			
DupMsgQueries  numeric(15,3),			
DupMsgResponses  numeric(15,3),			
DupMsgDetected  numeric(15,3),			
DupMsgTimeout  numeric(15,3),			
DupMsgOtherError  numeric(15,3),			
DupMsgSkipped  numeric(15,3),			
DupMsgDelReqs  numeric(15,3),			
SFBTHourlyBlocked  numeric(15,3),			
SFBTDailyBlocked  numeric(15,3),			
SFBTIncrements  numeric(15,3),			
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_SMS_Prepaid_Status(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
PPD_DebitRequest_Success  numeric(15,3),			
PPD_DebitRequest_Failure  numeric(15,3),			
PPD_QueryBalance_Success  numeric(15,3),			
PPD_QueryBalance_Failure  numeric(15,3),			
PPD_CreditRequest_Success  numeric(15,3),			
PPD_CreditRequest_Failure  numeric(15,3),			
PPD_Free_Messages  numeric(15,3),			
RDB_Writes_Sent  numeric(15,3),			
RDB_Write_Success  numeric(15,3),			
RDB_Write_Errors  numeric(15,3),			
RDB_Write_Failures  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_Prepaid_Failures(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
PPD_AllocationLost  numeric(15,3),			
PPD_ServerBusy  numeric(15,3),			
PPD_ProtocolViolations  numeric(15,3),			
PPD_InvalidMissParameter  numeric(15,3),			
PPD_InvalidSubscrDetails  numeric(15,3),			
PPD_ECommerceDisabled  numeric(15,3),			
PPD_InvalidMerchantId  numeric(15,3),			
PPD_SubscriberActivityBarred  numeric(15,3),			
PPD_CallsInProgress  numeric(15,3),			
PPD_WrongTypeMissBalance  numeric(15,3),			
PPD_UnsubscribedService  numeric(15,3),			
PPD_InsufficientFunds  numeric(15,3),			
PPD_UnknownError  numeric(15,3),			
PPD_InternalError  numeric(15,3),			
UC_TOD_Denial  numeric(15,3),			
UC_Other_Denial  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_PPD_Diam_Failures(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
PPD_RC_3004  numeric(15,3),			
PPD_RC_4010  numeric(15,3),			
PPD_RC_4012  numeric(15,3),			
PPD_RC_5003  numeric(15,3),			
PPD_RC_5004  numeric(15,3),			
PPD_RC_5005  numeric(15,3),			
PPD_RC_5012  numeric(15,3),			
PPD_RC_5030  numeric(15,3),			
PPD_RC_5031  numeric(15,3),			
Aux_10  numeric(15,3),			
Aux_11  numeric(15,3),			
Aux_12  numeric(15,3),			
Aux_13  numeric(15,3),			
Aux_14  numeric(15,3),			
Aux_15  numeric(15,3),			
PPD_InternalError  numeric(15,3),			
PPD_NoResponse  numeric(15,3),			
PPD_ProtocolError  numeric(15,3),			
PPD_PermanentFailure  numeric(15,3),			
PPD_UnknownError  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_SMS_Gen_Op(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
Billing_record_commit  numeric(15,3),			
Billing_record_failed  numeric(15,3),			
Msg_Status_Table_Size  numeric(15,3),			
Dlvry_Ack_created  numeric(15,3),			
Msg_Overload_Rjct  numeric(15,3),			
Msg_Status_Num_Inserts  numeric(15,3),			
Msg_Status_Num_Deletes  numeric(15,3),			
Green_Zone_Restrict  numeric(15,3),			
Signature_Success  numeric(15,3),			
Signature_Failure  numeric(15,3),			
Banner_Success  numeric(15,3),			
Banner_Failure  numeric(15,3),			
DelAckSuppress  numeric(15,3),			
LongMsgRelayTruncated  numeric(15,3),			
SCPR_Rcvd  numeric(15,3),			
Imsst_Received  numeric(15,3),			
Imsst_Success  numeric(15,3),			
InternalMsg_subType1  numeric(15,3),			
FDA_to_MDA  numeric(15,3),			
Direct_to_MDA  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_IMS_MO(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
SIP_Received  numeric(15,3),			
SIP_DecodeError  numeric(15,3),			
SIP_MsgP2P  numeric(15,3),			
SIP_RR_Success  numeric(15,3),			
SIP_RR_Failure  numeric(15,3),			
SIP_Sent  numeric(15,3),			
SIP_Not_Sent  numeric(15,3),			
SIP_Error_Returned  numeric(15,3),			
SIP_Submit_Recvd  numeric(15,3),			
SIP_RP_ACK_Recvd  numeric(15,3),			
SIP_RP_ERROR_Recvd  numeric(15,3),			
SIP_RP_SMMA_Recvd  numeric(15,3),			
SIP_RP_ACK_Sent  numeric(15,3),			
SIP_RP_ERROR_Sent  numeric(15,3),			
PNR_Received  numeric(15,3),			
PNA_NotSent  numeric(15,3),			
Aux_17  numeric(15,3),			
Aux_18  numeric(15,3),			
Aux_19  numeric(15,3),			
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_Msg_Delvrd_Hist(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
Total  numeric(15,3),			
Counter_1  numeric(15,3),			
Counter_2  numeric(15,3),			
Counter_3  numeric(15,3),			
Counter_4  numeric(15,3),			
Counter_5  numeric(15,3),			
Counter_6  numeric(15,3),			
Counter_7  numeric(15,3),			
Counter_8  numeric(15,3),			
Counter_9  numeric(15,3),			
Aux_11  numeric(15,3),			
Aux_12  numeric(15,3),			
Aux_13  numeric(15,3),			
Aux_14  numeric(15,3),			
Aux_15  numeric(15,3),			
Aux_16  numeric(15,3),			
Aux_17  numeric(15,3),			
Aux_18  numeric(15,3),			
Aux_19  numeric(15,3),			
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_Msg_Not_Delvrd_Hist(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
Total  numeric(15,3),			
Counter_1  numeric(15,3),			
Counter_2  numeric(15,3),			
Counter_3  numeric(15,3),			
Counter_4  numeric(15,3),			
Counter_5  numeric(15,3),			
Counter_6  numeric(15,3),			
Counter_7  numeric(15,3),			
Counter_8  numeric(15,3),			
Counter_9  numeric(15,3)
);


CREATE TABLE IF NOT EXISTS  SMSC.SDRS_External_Database(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
Queries_Sent  numeric(15,3),			
Query_Success  numeric(15,3),			
Query_NotFound  numeric(15,3),			
Query_Failures  numeric(15,3),			
Query_Errors  numeric(15,3),			
Query_Timeouts  numeric(15,3),			
Writes_Sent  numeric(15,3),			
Inserts_Sent  numeric(15,3),			
Updates_Sent  numeric(15,3),			
Deletes_Sent  numeric(15,3),			
Write_Success  numeric(15,3),			
Write_Failures  numeric(15,3),			
Write_Errors  numeric(15,3),			
Write_Timeouts  numeric(15,3),			
Queries_Received  numeric(15,3),			
Respond_Success  numeric(15,3),			
Respond_NotFound  numeric(15,3),			
Inserts_Received  numeric(15,3),			
Updates_Received  numeric(15,3),			
Deletes_Received  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_SDRS_Misc(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
QuarantineRqst  numeric(15,3),			
QuarantineFail  numeric(15,3),			
CloseReceived  numeric(15,3),			
CloseSuccess  numeric(15,3),			
Aux_5  numeric(15,3),			
Aux_6  numeric(15,3),			
Aux_7  numeric(15,3),			
Aux_8  numeric(15,3),			
Aux_9  numeric(15,3),			
Aux_10  numeric(15,3),			
Aux_11  numeric(15,3),			
Aux_12  numeric(15,3),			
Aux_13  numeric(15,3),			
Aux_14  numeric(15,3),			
Aux_15  numeric(15,3),			
Aux_16  numeric(15,3),			
Aux_17  numeric(15,3),			
Aux_18  numeric(15,3),			
Aux_19  numeric(15,3),			
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.SDRS_MME_Received(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
OFR_Submit_Received  numeric(15,3),			
OFR_Command_Received  numeric(15,3),			
OFR_Encoding_Error  numeric(15,3),			
OFR_Results_Sent  numeric(15,3),			
OFR_Error_Sent  numeric(15,3),			
ALR_Received  numeric(15,3),			
Aux_7  numeric(15,3),			
Aux_8  numeric(15,3),			
Aux_9  numeric(15,3),			
Aux_10  numeric(15,3),			
Aux_11  numeric(15,3),			
Aux_12  numeric(15,3),			
Aux_13  numeric(15,3),			
Aux_14  numeric(15,3),			
Aux_15  numeric(15,3),			
Aux_16  numeric(15,3),			
Aux_17  numeric(15,3),			
Aux_18  numeric(15,3),			
Aux_19  numeric(15,3),			
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.PORT_T_Comm_Status(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
TNPP_Allocation_Lost  numeric(15,3),				
TNPP_Duplicate_Pckt  numeric(15,3),				
TNPP_Page_Received  numeric(15,3),				
TNPP_Page_NotValid  numeric(15,3),				
TNPP_UPage_Received  numeric(15,3),				
TNPP_UPage_NotValid  numeric(15,3),				
TAP_Allocation_Lost  numeric(15,3),				
TAP_Page_Received  numeric(15,3),				
TAP_Page_NotValid  numeric(15,3),				
ETAP_Create_Received  numeric(15,3),				
ETAP_Query_Received  numeric(15,3),				
ETAP_Update_Received  numeric(15,3),				
ETAP_Delete_Received  numeric(15,3),				
Aux_14  numeric(15,3),				
Aux_15  numeric(15,3),				
Aux_16  numeric(15,3),				
Aux_17  numeric(15,3),				
Aux_18  numeric(15,3),				
Aux_19  numeric(15,3),				
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.PORT_Octel_Comm_Status(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
Octel_Alloc_Failure  numeric(15,3),			
Octel_Alloc_Lost  numeric(15,3),			
Octel_Signon_Failure  numeric(15,3),			
Octel_Ready_Failure  numeric(15,3),			
Octel_Internal_Error  numeric(15,3),			
Octel_VMN_Rcvd  numeric(15,3),			
Octel_VMN_NotValid  numeric(15,3),			
Octel_Page_Rcvd  numeric(15,3),			
Octel_Page_NotValid  numeric(15,3),			
Aux_10  numeric(15,3),			
Aux_11  numeric(15,3),			
Aux_12  numeric(15,3),			
Aux_13  numeric(15,3),			
Aux_14  numeric(15,3),			
Aux_15  numeric(15,3),			
Aux_16  numeric(15,3),			
Aux_17  numeric(15,3),			
Aux_18  numeric(15,3),			
Aux_19  numeric(15,3),			
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.PORT_SMPP_Msg_Status(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
SMPP_MWI_Rcvd  numeric(15,3),			
SMPP_Page_Rcvd  numeric(15,3),			
SMPP_Pass_Rcvd  numeric(15,3),			
SMPP_WAP_Rcvd  numeric(15,3),			
SMPP_LBS_Rcvd  numeric(15,3),			
SMPP_Query  numeric(15,3),			
SMPP_Cancel  numeric(15,3),			
SMPP_Replace  numeric(15,3),			
SMPP_CellBrdcst_Rcvd  numeric(15,3),			
SMPP_EMS_Rcvd  numeric(15,3),			
WAP_Subtype_1  numeric(15,3),			
SCPD_Rcvd  numeric(15,3),			
Msg_Overload_Rjct  numeric(15,3),			
SMPP_to_ESME  numeric(15,3),			
SMPP_Unsent_Full  numeric(15,3),			
SMPP_Acks  numeric(15,3),			
SMPP_Allocation_Lost  numeric(15,3),			
SMPP_Bind_Failure  numeric(15,3),			
SMPP_No_Enq_Ack  numeric(15,3),			
SMPP_Packets_Dropped  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.PORT_SMPPQ_Stats(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
I_Attempt  numeric(15,3),			
I_Success  numeric(15,3),			
I_E_Dup_Key  numeric(15,3),			
I_E_Limit_Reached  numeric(15,3),			
I_E_Internal_Err  numeric(15,3),			
I_E_Time_Out  numeric(15,3),			
I_Other_Fail  numeric(15,3),			
R_Attempt  numeric(15,3),			
R_Success  numeric(15,3),			
R_E_Tuple_Not_Found  numeric(15,3),			
R_E_Internal_Err  numeric(15,3),			
R_E_Time_Out  numeric(15,3),			
R_Other_Fail  numeric(15,3),			
D_Attempt  numeric(15,3),			
D_Success  numeric(15,3),			
D_E_Tuple_Not_Found  numeric(15,3),			
D_E_Internal_Err  numeric(15,3),			
D_E_Time_Out  numeric(15,3),			
D_Other_Fail  numeric(15,3),			
Aux_20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.STAR_SMPP_Msg_Status(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
SMPP_MWI_Rcvd  numeric(15,3),
SMPP_Page_Rcvd  numeric(15,3),
SMPP_Pass_Rcvd  numeric(15,3),
SMPP_WAP_Rcvd  numeric(15,3),
SMPP_LBS_Rcvd  numeric(15,3),
SMPP_Query  numeric(15,3),
SMPP_Cancel  numeric(15,3),
SMPP_Replace  numeric(15,3),
SMPP_CellBrdcst_Rcvd  numeric(15,3),
SMPP_EMS_Rcvd  numeric(15,3),
WAP_Subtype_1  numeric(15,3),
SCPD_Rcvd  numeric(15,3),
Msg_Overload_Rjct  numeric(15,3),
SMPP_to_ESME  numeric(15,3),
SMPP_Unsent_Full  numeric(15,3),
SMPP_Acks  numeric(15,3),
SMPP_Allocation_Lost  numeric(15,3),
SMPP_Bind_Failure  numeric(15,3),
SMPP_No_Enq_Ack  numeric(15,3),
SMPP_Packets_Dropped  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.MCNT_MCNT_Stats(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
DB_Queries  numeric(15,3),				
DB_Responses  numeric(15,3),				
DB_Reads  numeric(15,3),				
DB_Replaces  numeric(15,3),				
DB_Inserts  numeric(15,3),				
DB_Deletes  numeric(15,3),				
DB_Audits  numeric(15,3),				
DB_ReplaceErr  numeric(15,3),				
DB_InsertErr  numeric(15,3),				
DB_DeleteErr  numeric(15,3),				
DB_Aux11  numeric(15,3),				
DB_Aux12  numeric(15,3),				
DB_Aux13  numeric(15,3),				
DB_Aux14  numeric(15,3),				
DB_Aux15  numeric(15,3),				
DB_Aux16  numeric(15,3),				
DB_Aux17  numeric(15,3),				
DB_Aux18  numeric(15,3),				
DB_Aux19  numeric(15,3),				
DB_Aux20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.MCNT_DupDB_Stats(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
DB_Queries  numeric(15,3),			
DB_Responses  numeric(15,3),			
DB_Dups  numeric(15,3),			
DB_Errs  numeric(15,3),			
DB_Reads  numeric(15,3),			
DB_Inserts  numeric(15,3),			
DB_Deletes  numeric(15,3),			
DB_Updates  numeric(15,3),			
DB_Audits  numeric(15,3),			
DB_ReadErr  numeric(15,3),			
DB_InsertErr  numeric(15,3),			
DB_DeleteErr  numeric(15,3),			
DB_UpdateErr  numeric(15,3),			
DB_Aux14  numeric(15,3),			
DB_Aux15  numeric(15,3),			
DB_Aux16  numeric(15,3),			
DB_Aux17  numeric(15,3),			
DB_Aux18  numeric(15,3),			
DB_Aux19  numeric(15,3),			
DB_Aux20  numeric(15,3)
);

CREATE TABLE IF NOT EXISTS  SMSC.MCNT_FinalDispDB_Stats(
site varchar(20),
SchedTime TIMESTAMP,
ActualTime TIMESTAMP,
Duration VARCHAR(15),
Machine VARCHAR(15),
DV_Queries  numeric(15,3),			
DV_Responses  numeric(15,3),			
DV_Reads  numeric(15,3),			
DV_Inserts  numeric(15,3),			
DV_ReadErr  numeric(15,3),			
DV_InsertErr  numeric(15,3),			
DB_Reads  numeric(15,3),			
DB_Inserts  numeric(15,3),			
DB_Deletes  numeric(15,3),			
DB_Audits  numeric(15,3),			
DB_ReadErr  numeric(15,3),			
DB_InsertErr  numeric(15,3),			
DB_DeleteErr  numeric(15,3),			
DB_Aux14  numeric(15,3),			
DB_Aux15  numeric(15,3),			
DB_Aux16  numeric(15,3),			
DB_Aux17  numeric(15,3),			
DB_Aux18  numeric(15,3),			
DB_Aux19  numeric(15,3),			
DB_Aux20  numeric(15,3)
);

create table if not exists SMSC.SPA_merge(
schedTimeHour int,
schedTimeDay date,
site varchar(20), 
Machine varchar(15),
MCNT_DupDB_Stats_DB_Queries numeric(15,3),
MCNT_DupDB_Stats_DB_Responses numeric(15,3),
MCNT_DupDB_Stats_DB_Dups numeric(15,3),
MCNT_DupDB_Stats_DB_Errs numeric(15,3),
MCNT_DupDB_Stats_DB_Reads numeric(15,3),
MCNT_DupDB_Stats_DB_Inserts numeric(15,3),
MCNT_DupDB_Stats_DB_Deletes numeric(15,3),
MCNT_DupDB_Stats_DB_Updates numeric(15,3),
MCNT_DupDB_Stats_DB_Audits numeric(15,3),
MCNT_DupDB_Stats_DB_ReadErr numeric(15,3),
MCNT_DupDB_Stats_DB_InsertErr numeric(15,3),
MCNT_DupDB_Stats_DB_DeleteErr numeric(15,3),
MCNT_DupDB_Stats_DB_UpdateErr numeric(15,3),
MCNT_DupDB_Stats_DB_Aux14 numeric(15,3),
MCNT_DupDB_Stats_DB_Aux15 numeric(15,3),
MCNT_DupDB_Stats_DB_Aux16 numeric(15,3),MCNT_DupDB_Stats_DB_Aux17 numeric(15,3),MCNT_DupDB_Stats_DB_Aux18 numeric(15,3),MCNT_DupDB_Stats_DB_Aux19 numeric(15,3),MCNT_DupDB_Stats_DB_Aux20 numeric(15,3),MCNT_FinalDispDB_Stats_DV_Queries numeric(15,3),MCNT_FinalDispDB_Stats_DV_Responses numeric(15,3),MCNT_FinalDispDB_Stats_DV_Reads numeric(15,3),MCNT_FinalDispDB_Stats_DV_Inserts numeric(15,3),MCNT_FinalDispDB_Stats_DV_ReadErr numeric(15,3),MCNT_FinalDispDB_Stats_DV_InsertErr numeric(15,3),MCNT_FinalDispDB_Stats_DB_Reads numeric(15,3),MCNT_FinalDispDB_Stats_DB_Inserts numeric(15,3),MCNT_FinalDispDB_Stats_DB_Deletes numeric(15,3),MCNT_FinalDispDB_Stats_DB_Audits numeric(15,3),MCNT_FinalDispDB_Stats_DB_ReadErr numeric(15,3),MCNT_FinalDispDB_Stats_DB_InsertErr numeric(15,3),MCNT_FinalDispDB_Stats_DB_DeleteErr numeric(15,3),MCNT_FinalDispDB_Stats_DB_Aux14 numeric(15,3),MCNT_FinalDispDB_Stats_DB_Aux15 numeric(15,3),MCNT_FinalDispDB_Stats_DB_Aux16 numeric(15,3),MCNT_FinalDispDB_Stats_DB_Aux17 numeric(15,3),MCNT_FinalDispDB_Stats_DB_Aux18 numeric(15,3),MCNT_FinalDispDB_Stats_DB_Aux19 numeric(15,3),MCNT_FinalDispDB_Stats_DB_Aux20 numeric(15,3),MCNT_MCNT_Stats_DB_Queries numeric(15,3),MCNT_MCNT_Stats_DB_Responses numeric(15,3),MCNT_MCNT_Stats_DB_Reads numeric(15,3),MCNT_MCNT_Stats_DB_Replaces numeric(15,3),MCNT_MCNT_Stats_DB_Inserts numeric(15,3),MCNT_MCNT_Stats_DB_Deletes numeric(15,3),MCNT_MCNT_Stats_DB_Audits numeric(15,3),MCNT_MCNT_Stats_DB_ReplaceErr numeric(15,3),MCNT_MCNT_Stats_DB_InsertErr numeric(15,3),MCNT_MCNT_Stats_DB_DeleteErr numeric(15,3),MCNT_MCNT_Stats_DB_Aux11 numeric(15,3),MCNT_MCNT_Stats_DB_Aux12 numeric(15,3),MCNT_MCNT_Stats_DB_Aux13 numeric(15,3),MCNT_MCNT_Stats_DB_Aux14 numeric(15,3),MCNT_MCNT_Stats_DB_Aux15 numeric(15,3),MCNT_MCNT_Stats_DB_Aux16 numeric(15,3),MCNT_MCNT_Stats_DB_Aux17 numeric(15,3),MCNT_MCNT_Stats_DB_Aux18 numeric(15,3),MCNT_MCNT_Stats_DB_Aux19 numeric(15,3),MCNT_MCNT_Stats_DB_Aux20 numeric(15,3),MMDS_Data_Stats_Free_List_size numeric(15,3),MMDS_Data_Stats_MIN_Index_size numeric(15,3),MMDS_Data_Stats_Util_TBR numeric(15,3),MMDS_Data_Stats_DlvryInit_New numeric(15,3),MMDS_Data_Stats_DlvryInit_Notify numeric(15,3),MMDS_Data_Stats_DlvryInit_TBR numeric(15,3),MMDS_Data_Stats_DlvryInit_Sync numeric(15,3),MMDS_Data_Stats_DlvryInit_N_Discard numeric(15,3),MMDS_Data_Stats_DlvryInit_unkwn numeric(15,3),MMDS_Data_Stats_SS7_New_Msg_Timeout numeric(15,3),MMDS_Data_Stats_SS7_Extend_Given numeric(15,3),MMDS_Data_Stats_SS7_Hung_Call_Detect numeric(15,3),MMDS_Data_Stats_SS7 numeric(15,3),MMDS_Data_Stats_SS7_First_Attempts numeric(15,3),MMDS_Data_Stats_SS7_Immediate numeric(15,3),MMDS_Data_Stats_PreSplitMinDPP_Atmpt numeric(15,3),MMDS_Data_Stats_PreSplitMinDPP_Err numeric(15,3),MMDS_Data_Stats_SS7_Trans_Not_Avail numeric(15,3),MMDS_Data_Stats_CellArrival numeric(15,3),MMDS_Data_Stats_Escalate_after_SS7 numeric(15,3),MMDS_GSM_IMS_Stats_SRI_Send_Total numeric(15,3),MMDS_GSM_IMS_Stats_SRI_Success numeric(15,3),MMDS_GSM_IMS_Stats_InfoSCReceived_Total numeric(15,3),MMDS_GSM_IMS_Stats_MT_FSM_Send_Total numeric(15,3),MMDS_GSM_IMS_Stats_MT_FSM_Success numeric(15,3),MMDS_GSM_IMS_Stats_RptSM_Send_Total numeric(15,3),MMDS_GSM_IMS_Stats_RptSM_Success numeric(15,3),MMDS_GSM_IMS_Stats_UDR_Invoke numeric(15,3),MMDS_GSM_IMS_Stats_UDR_Not_Sent numeric(15,3),MMDS_GSM_IMS_Stats_UDR_Error_Returned numeric(15,3),MMDS_GSM_IMS_Stats_SIP_Invoke numeric(15,3),MMDS_GSM_IMS_Stats_SIP_Not_Sent numeric(15,3),MMDS_GSM_IMS_Stats_SIP_Error_Returned numeric(15,3),MMDS_GSM_IMS_Stats_SNR_Subscribe_sent numeric(15,3),MMDS_GSM_IMS_Stats_SNR_Unsubscribe_sent numeric(15,3),MMDS_GSM_IMS_Stats_SNR_failed numeric(15,3),MMDS_GSM_IMS_Stats_SMS_Ack_ignored numeric(15,3),MMDS_GSM_IMS_Stats_SS7_Fallback_Success numeric(15,3),MMDS_GSM_IMS_Stats_SIP_GSM_Deliver numeric(15,3),MMDS_GSM_IMS_Stats_SIP_GSM_StatusReport numeric(15,3),MMDS_IS41_Stats_SMSRqst_Invoke numeric(15,3),MMDS_IS41_Stats_SMSRqst_RR_Success numeric(15,3),MMDS_IS41_Stats_SMSRqst_RR_Denied numeric(15,3),MMDS_IS41_Stats_SMSRqst_RR_Delayed numeric(15,3),MMDS_IS41_Stats_SMSRqst_RR_Failure numeric(15,3),MMDS_IS41_Stats_SMSRqst_RR_OtherErr numeric(15,3),MMDS_IS41_Stats_SMSRqst_NS_NotSent numeric(15,3),MMDS_IS41_Stats_SMSRqst_ER_Unkwn_MIN numeric(15,3),MMDS_IS41_Stats_SMSRqst_ER_ErrorRtrn numeric(15,3),MMDS_IS41_Stats_SMSDPP_Invoke numeric(15,3),MMDS_IS41_Stats_SMSDPP_Success numeric(15,3),MMDS_IS41_Stats_SMSDPP_RR numeric(15,3),MMDS_IS41_Stats_SMSDPP_Not_Sent numeric(15,3),MMDS_IS41_Stats_SMSDPP_Error_Returned numeric(15,3),MMDS_IS41_Stats_SMSNotify_Invoke numeric(15,3),MMDS_IS41_Stats_To_SMSC_Success numeric(15,3),MMDS_IS41_Stats_To_SMSC_Dpp_Attempts numeric(15,3),MMDS_IS41_Stats_InfoDir_Invoke numeric(15,3),MMDS_IS41_Stats_MsgDir_Invoke numeric(15,3),MMDS_IS41_Stats_SMSDPP_Cell_Success numeric(15,3),MMDS_MME_Stats_SRR_Send_Total numeric(15,3),MMDS_MME_Stats_SRR_Success numeric(15,3),MMDS_MME_Stats_TFR_Send_Total numeric(15,3),MMDS_MME_Stats_TFR_Success numeric(15,3),MMDS_MME_Stats_RDR_Send_Total numeric(15,3),MMDS_MME_Stats_RDR_Success numeric(15,3),MMDS_MME_Stats_DelivRep_Recvd numeric(15,3),MMDS_MME_Stats_Aux_8 numeric(15,3),MMDS_MME_Stats_Aux_9 numeric(15,3),MMDS_MME_Stats_Aux_10 numeric(15,3),MMDS_MME_Stats_Aux_11 numeric(15,3),MMDS_MME_Stats_Aux_12 numeric(15,3),MMDS_MME_Stats_Aux_13 numeric(15,3),MMDS_MME_Stats_Aux_14 numeric(15,3),MMDS_MME_Stats_Aux_15 numeric(15,3),MMDS_MME_Stats_Aux_16 numeric(15,3),MMDS_MME_Stats_Aux_17 numeric(15,3),MMDS_MME_Stats_Aux_18 numeric(15,3),MMDS_MME_Stats_Aux_19 numeric(15,3),MMDS_MME_Stats_Aux_20 numeric(15,3),MMDS_MSGQ_Ins_and_Read_I_Attempt numeric(15,3),MMDS_MSGQ_Ins_and_Read_I_Success numeric(15,3),MMDS_MSGQ_Ins_and_Read_I_E_Dup_Key numeric(15,3),MMDS_MSGQ_Ins_and_Read_I_E_Limit_Reached numeric(15,3),MMDS_MSGQ_Ins_and_Read_I_E_Internal_Err numeric(15,3),MMDS_MSGQ_Ins_and_Read_I_E_Time_Out numeric(15,3),MMDS_MSGQ_Ins_and_Read_I_Other_Fail numeric(15,3),MMDS_MSGQ_Ins_and_Read_R_Attempt numeric(15,3),MMDS_MSGQ_Ins_and_Read_R_Success numeric(15,3),MMDS_MSGQ_Ins_and_Read_R_E_Tuple_Not_Found numeric(15,3),MMDS_MSGQ_Ins_and_Read_R_E_Internal_Err numeric(15,3),MMDS_MSGQ_Ins_and_Read_R_E_Time_Out numeric(15,3),MMDS_MSGQ_Ins_and_Read_R_Other_Fail numeric(15,3),MMDS_MSGQ_Ins_and_Read_Aux_14 numeric(15,3),MMDS_MSGQ_Ins_and_Read_Aux_15 numeric(15,3),MMDS_MSGQ_Ins_and_Read_Alt_IF_Used numeric(15,3),MMDS_MSGQ_Ins_and_Read_Alt_IF_CDMA numeric(15,3),MMDS_MSGQ_Ins_and_Read_Alt_IF_GSM numeric(15,3),MMDS_MSGQ_Ins_and_Read_Alt_IF_Rmvd numeric(15,3),MMDS_MSGQ_Ins_and_Read_Alt_IF_Churn numeric(15,3),MMDS_MSGQ_Update_Del_U_Attempt numeric(15,3),MMDS_MSGQ_Update_Del_U_Success numeric(15,3),MMDS_MSGQ_Update_Del_U_E_Tuple_Not_Found numeric(15,3),MMDS_MSGQ_Update_Del_U_E_Internal_Err numeric(15,3),MMDS_MSGQ_Update_Del_U_E_Time_Out numeric(15,3),MMDS_MSGQ_Update_Del_U_Other_Fail numeric(15,3),MMDS_MSGQ_Update_Del_D_Attempt numeric(15,3),MMDS_MSGQ_Update_Del_D_Success numeric(15,3),MMDS_MSGQ_Update_Del_D_E_Tuple_Not_Found numeric(15,3),MMDS_MSGQ_Update_Del_D_E_Internal_Err numeric(15,3),MMDS_MSGQ_Update_Del_D_E_Time_Out numeric(15,3),MMDS_MSGQ_Update_Del_D_Other_Fail numeric(15,3),MMDS_MSGQ_Update_Del_Aux_13 numeric(15,3),MMDS_MSGQ_Update_Del_Aux_14 numeric(15,3),MMDS_MSGQ_Update_Del_Aux_15 numeric(15,3),MMDS_MSGQ_Update_Del_Aux_16 numeric(15,3),MMDS_MSGQ_Update_Del_Aux_17 numeric(15,3),MMDS_MSGQ_Update_Del_Aux_18 numeric(15,3),MMDS_MSGQ_Update_Del_Aux_19 numeric(15,3),MMDS_MSGQ_Update_Del_Aux_20 numeric(15,3),MMDS_Msg_Delvrd_Hist_Total numeric(15,3),MMDS_Msg_Delvrd_Hist_Counter_1 numeric(15,3),MMDS_Msg_Delvrd_Hist_Counter_2 numeric(15,3),MMDS_Msg_Delvrd_Hist_Counter_3 numeric(15,3),MMDS_Msg_Delvrd_Hist_Counter_4 numeric(15,3),MMDS_Msg_Delvrd_Hist_Counter_5 numeric(15,3),MMDS_Msg_Delvrd_Hist_Counter_6 numeric(15,3),MMDS_Msg_Delvrd_Hist_Counter_7 numeric(15,3),MMDS_Msg_Delvrd_Hist_Counter_8 numeric(15,3),MMDS_Msg_Delvrd_Hist_Counter_9 numeric(15,3),MMDS_Msg_Delvrd_Hist_Aux_11 numeric(15,3),MMDS_Msg_Delvrd_Hist_Aux_12 numeric(15,3),MMDS_Msg_Delvrd_Hist_Aux_13 numeric(15,3),MMDS_Msg_Delvrd_Hist_Aux_14 numeric(15,3),MMDS_Msg_Delvrd_Hist_Aux_15 numeric(15,3),MMDS_Msg_Delvrd_Hist_Aux_16 numeric(15,3),MMDS_Msg_Delvrd_Hist_Aux_17 numeric(15,3),MMDS_Msg_Delvrd_Hist_Aux_18 numeric(15,3),MMDS_Msg_Delvrd_Hist_Aux_19 numeric(15,3),MMDS_Msg_Delvrd_Hist_Aux_20 numeric(15,3),MMDS_PPD_Diam_Failures_PPD_RC_3004 numeric(15,3),MMDS_PPD_Diam_Failures_PPD_RC_4010 numeric(15,3),MMDS_PPD_Diam_Failures_PPD_RC_4012 numeric(15,3),MMDS_PPD_Diam_Failures_PPD_RC_5003 numeric(15,3),MMDS_PPD_Diam_Failures_PPD_RC_5004 numeric(15,3),MMDS_PPD_Diam_Failures_PPD_RC_5005 numeric(15,3),MMDS_PPD_Diam_Failures_PPD_RC_5012 numeric(15,3),MMDS_PPD_Diam_Failures_PPD_RC_5030 numeric(15,3),MMDS_PPD_Diam_Failures_PPD_RC_5031 numeric(15,3),MMDS_PPD_Diam_Failures_Aux_10 numeric(15,3),MMDS_PPD_Diam_Failures_Aux_11 numeric(15,3),MMDS_PPD_Diam_Failures_Aux_12 numeric(15,3),MMDS_PPD_Diam_Failures_Aux_13 numeric(15,3),MMDS_PPD_Diam_Failures_Aux_14 numeric(15,3),MMDS_PPD_Diam_Failures_Aux_15 numeric(15,3),MMDS_PPD_Diam_Failures_PPD_InternalError numeric(15,3),MMDS_PPD_Diam_Failures_PPD_NoResponse numeric(15,3),MMDS_PPD_Diam_Failures_PPD_ProtocolError numeric(15,3),MMDS_PPD_Diam_Failures_PPD_PermanentFailure numeric(15,3),MMDS_PPD_Diam_Failures_PPD_UnknownError numeric(15,3),MMDS_Prepaid_Failures_PPD_AllocationLost numeric(15,3),MMDS_Prepaid_Failures_PPD_ServerBusy numeric(15,3),MMDS_Prepaid_Failures_PPD_ProtocolViolations numeric(15,3),MMDS_Prepaid_Failures_PPD_InvalidMissParameter numeric(15,3),MMDS_Prepaid_Failures_PPD_InvalidSubscrDetails numeric(15,3),MMDS_Prepaid_Failures_PPD_ECommerceDisabled numeric(15,3),MMDS_Prepaid_Failures_PPD_InvalidMerchantId numeric(15,3),MMDS_Prepaid_Failures_PPD_SubscriberActivityBarred numeric(15,3),MMDS_Prepaid_Failures_PPD_CallsInProgress numeric(15,3),MMDS_Prepaid_Failures_PPD_WrongTypeMissBalance numeric(15,3),MMDS_Prepaid_Failures_PPD_UnsubscribedService numeric(15,3),MMDS_Prepaid_Failures_PPD_InsufficientFunds numeric(15,3),MMDS_Prepaid_Failures_PPD_UnknownError numeric(15,3),MMDS_Prepaid_Failures_PPD_InternalError numeric(15,3),MMDS_Prepaid_Failures_UC_TOD_Denial numeric(15,3),MMDS_Prepaid_Failures_UC_Other_Denial numeric(15,3),MMDS_SMS_Gen_Op_Billing_record_commit numeric(15,3),MMDS_SMS_Gen_Op_Billing_record_failed numeric(15,3),MMDS_SMS_Gen_Op_Msg_Status_Table_Size numeric(15,3),MMDS_SMS_Gen_Op_Dlvry_Ack_created numeric(15,3),MMDS_SMS_Gen_Op_Msg_Overload_Rjct numeric(15,3),MMDS_SMS_Gen_Op_Msg_Status_Num_Inserts numeric(15,3),MMDS_SMS_Gen_Op_Msg_Status_Num_Deletes numeric(15,3),MMDS_SMS_Gen_Op_Green_Zone_Restrict numeric(15,3),MMDS_SMS_Gen_Op_Signature_Success numeric(15,3),MMDS_SMS_Gen_Op_Signature_Failure numeric(15,3),MMDS_SMS_Gen_Op_Banner_Success numeric(15,3),MMDS_SMS_Gen_Op_Banner_Failure numeric(15,3),MMDS_SMS_Gen_Op_DelAckSuppress numeric(15,3),MMDS_SMS_Gen_Op_LongMsgRelayTruncated numeric(15,3),MMDS_SMS_Gen_Op_SCPR_Rcvd numeric(15,3),MMDS_SMS_Gen_Op_Imsst_Received numeric(15,3),MMDS_SMS_Gen_Op_Imsst_Success numeric(15,3),MMDS_SMS_Gen_Op_InternalMsg_subType1 numeric(15,3),MMDS_SMS_Gen_Op_FDA_to_MDA numeric(15,3),MMDS_SMS_Gen_Op_MO_Escalate_after_SS7 numeric(15,3),MMDS_SMS_Prepaid_Status_PPD_DebitRequest_Success numeric(15,3),MMDS_SMS_Prepaid_Status_PPD_DebitRequest_Failure numeric(15,3),MMDS_SMS_Prepaid_Status_PPD_QueryBalance_Success numeric(15,3),MMDS_SMS_Prepaid_Status_PPD_QueryBalance_Failure numeric(15,3),MMDS_SMS_Prepaid_Status_PPD_CreditRequest_Success numeric(15,3),MMDS_SMS_Prepaid_Status_PPD_CreditRequest_Failure numeric(15,3),MMDS_SMS_Prepaid_Status_PPD_Free_Messages numeric(15,3),MMDS_SMS_Prepaid_Status_RDB_Writes_Sent numeric(15,3),MMDS_SMS_Prepaid_Status_RDB_Write_Success numeric(15,3),MMDS_SMS_Prepaid_Status_RDB_Write_Errors numeric(15,3),MMDS_SMS_Prepaid_Status_RDB_Write_Failures numeric(15,3),PORT_Octel_Comm_Status_Octel_Alloc_Failure numeric(15,3),PORT_Octel_Comm_Status_Octel_Alloc_Lost numeric(15,3),PORT_Octel_Comm_Status_Octel_Signon_Failure numeric(15,3),PORT_Octel_Comm_Status_Octel_Ready_Failure numeric(15,3),PORT_Octel_Comm_Status_Octel_Internal_Error numeric(15,3),PORT_Octel_Comm_Status_Octel_VMN_Rcvd numeric(15,3),PORT_Octel_Comm_Status_Octel_VMN_NotValid numeric(15,3),PORT_Octel_Comm_Status_Octel_Page_Rcvd numeric(15,3),PORT_Octel_Comm_Status_Octel_Page_NotValid numeric(15,3),PORT_Octel_Comm_Status_Aux_10 numeric(15,3),PORT_Octel_Comm_Status_Aux_11 numeric(15,3),PORT_Octel_Comm_Status_Aux_12 numeric(15,3),PORT_Octel_Comm_Status_Aux_13 numeric(15,3),PORT_Octel_Comm_Status_Aux_14 numeric(15,3),PORT_Octel_Comm_Status_Aux_15 numeric(15,3),PORT_Octel_Comm_Status_Aux_16 numeric(15,3),PORT_Octel_Comm_Status_Aux_17 numeric(15,3),PORT_Octel_Comm_Status_Aux_18 numeric(15,3),PORT_Octel_Comm_Status_Aux_19 numeric(15,3),PORT_Octel_Comm_Status_Aux_20 numeric(15,3),PORT_SMPPQ_Stats_I_Attempt numeric(15,3),PORT_SMPPQ_Stats_I_Success numeric(15,3),PORT_SMPPQ_Stats_I_E_Dup_Key numeric(15,3),PORT_SMPPQ_Stats_I_E_Limit_Reached numeric(15,3),PORT_SMPPQ_Stats_I_E_Internal_Err numeric(15,3),PORT_SMPPQ_Stats_I_E_Time_Out numeric(15,3),PORT_SMPPQ_Stats_I_Other_Fail numeric(15,3),PORT_SMPPQ_Stats_R_Attempt numeric(15,3),PORT_SMPPQ_Stats_R_Success numeric(15,3),PORT_SMPPQ_Stats_R_E_Tuple_Not_Found numeric(15,3),PORT_SMPPQ_Stats_R_E_Internal_Err numeric(15,3),PORT_SMPPQ_Stats_R_E_Time_Out numeric(15,3),PORT_SMPPQ_Stats_R_Other_Fail numeric(15,3),PORT_SMPPQ_Stats_D_Attempt numeric(15,3),PORT_SMPPQ_Stats_D_Success numeric(15,3),PORT_SMPPQ_Stats_D_E_Tuple_Not_Found numeric(15,3),PORT_SMPPQ_Stats_D_E_Internal_Err numeric(15,3),PORT_SMPPQ_Stats_D_E_Time_Out numeric(15,3),PORT_SMPPQ_Stats_D_Other_Fail numeric(15,3),PORT_SMPPQ_Stats_Aux_20 numeric(15,3),PORT_SMPP_Msg_Status_SMPP_MWI_Rcvd numeric(15,3),PORT_SMPP_Msg_Status_SMPP_Page_Rcvd numeric(15,3),PORT_SMPP_Msg_Status_SMPP_Pass_Rcvd numeric(15,3),PORT_SMPP_Msg_Status_SMPP_WAP_Rcvd numeric(15,3),PORT_SMPP_Msg_Status_SMPP_LBS_Rcvd numeric(15,3),PORT_SMPP_Msg_Status_SMPP_Query numeric(15,3),PORT_SMPP_Msg_Status_SMPP_Cancel numeric(15,3),PORT_SMPP_Msg_Status_SMPP_Replace numeric(15,3),PORT_SMPP_Msg_Status_SMPP_CellBrdcst_Rcvd numeric(15,3),PORT_SMPP_Msg_Status_SMPP_EMS_Rcvd numeric(15,3),PORT_SMPP_Msg_Status_WAP_Subtype_1 numeric(15,3),PORT_SMPP_Msg_Status_SCPD_Rcvd numeric(15,3),PORT_SMPP_Msg_Status_Msg_Overload_Rjct numeric(15,3),PORT_SMPP_Msg_Status_SMPP_to_ESME numeric(15,3),PORT_SMPP_Msg_Status_SMPP_Unsent_Full numeric(15,3),PORT_SMPP_Msg_Status_SMPP_Acks numeric(15,3),PORT_SMPP_Msg_Status_SMPP_Allocation_Lost numeric(15,3),PORT_SMPP_Msg_Status_SMPP_Bind_Failure numeric(15,3),PORT_SMPP_Msg_Status_SMPP_No_Enq_Ack numeric(15,3),PORT_SMPP_Msg_Status_SMPP_Packets_Dropped numeric(15,3),PORT_T_Comm_Status_TNPP_Allocation_Lost numeric(15,3),PORT_T_Comm_Status_TNPP_Duplicate_Pckt numeric(15,3),PORT_T_Comm_Status_TNPP_Page_Received numeric(15,3),PORT_T_Comm_Status_TNPP_Page_NotValid numeric(15,3),PORT_T_Comm_Status_TNPP_UPage_Received numeric(15,3),PORT_T_Comm_Status_TNPP_UPage_NotValid numeric(15,3),PORT_T_Comm_Status_TAP_Allocation_Lost numeric(15,3),PORT_T_Comm_Status_TAP_Page_Received numeric(15,3),PORT_T_Comm_Status_TAP_Page_NotValid numeric(15,3),PORT_T_Comm_Status_ETAP_Create_Received numeric(15,3),PORT_T_Comm_Status_ETAP_Query_Received numeric(15,3),PORT_T_Comm_Status_ETAP_Update_Received numeric(15,3),PORT_T_Comm_Status_ETAP_Delete_Received numeric(15,3),PORT_T_Comm_Status_Aux_14 numeric(15,3),PORT_T_Comm_Status_Aux_15 numeric(15,3),PORT_T_Comm_Status_Aux_16 numeric(15,3),PORT_T_Comm_Status_Aux_17 numeric(15,3),PORT_T_Comm_Status_Aux_18 numeric(15,3),PORT_T_Comm_Status_Aux_19 numeric(15,3),PORT_T_Comm_Status_Aux_20 numeric(15,3),SDRS_External_Database_Queries_Sent numeric(15,3),SDRS_External_Database_Query_Success numeric(15,3),SDRS_External_Database_Query_NotFound numeric(15,3),SDRS_External_Database_Query_Failures numeric(15,3),SDRS_External_Database_Query_Errors numeric(15,3),SDRS_External_Database_Query_Timeouts numeric(15,3),SDRS_External_Database_Writes_Sent numeric(15,3),SDRS_External_Database_Inserts_Sent numeric(15,3),SDRS_External_Database_Updates_Sent numeric(15,3),SDRS_External_Database_Deletes_Sent numeric(15,3),SDRS_External_Database_Write_Success numeric(15,3),SDRS_External_Database_Write_Failures numeric(15,3),SDRS_External_Database_Write_Errors numeric(15,3),SDRS_External_Database_Write_Timeouts numeric(15,3),SDRS_External_Database_Queries_Received numeric(15,3),SDRS_External_Database_Respond_Success numeric(15,3),SDRS_External_Database_Respond_NotFound numeric(15,3),SDRS_External_Database_Inserts_Received numeric(15,3),SDRS_External_Database_Updates_Received numeric(15,3),SDRS_External_Database_Deletes_Received numeric(15,3),SDRS_Filter_List_Status_WHTListSearches numeric(15,3),SDRS_Filter_List_Status_WHTListRejects numeric(15,3),SDRS_Filter_List_Status_GlobalWHTListAccepts numeric(15,3),SDRS_Filter_List_Status_BLKListSearches numeric(15,3),SDRS_Filter_List_Status_BLKListRejects numeric(15,3),SDRS_Filter_List_Status_BlockedByRating numeric(15,3),SDRS_Filter_List_Status_DelayedResponse numeric(15,3),SDRS_Filter_List_Status_WrongResponse numeric(15,3),SDRS_Filter_List_Status_EmptyMessage numeric(15,3),SDRS_Filter_List_Status_DupMsgQueries numeric(15,3),SDRS_Filter_List_Status_DupMsgResponses numeric(15,3),SDRS_Filter_List_Status_DupMsgDetected numeric(15,3),SDRS_Filter_List_Status_DupMsgTimeout numeric(15,3),SDRS_Filter_List_Status_DupMsgOtherError numeric(15,3),SDRS_Filter_List_Status_DupMsgSkipped numeric(15,3),SDRS_Filter_List_Status_DupMsgDelReqs numeric(15,3),SDRS_Filter_List_Status_SFBTHourlyBlocked numeric(15,3),SDRS_Filter_List_Status_SFBTDailyBlocked numeric(15,3),SDRS_Filter_List_Status_SFBTIncrements numeric(15,3),SDRS_Filter_List_Status_Aux_20 numeric(15,3),SDRS_GSM_Received_MO_FSM_Received_Totl numeric(15,3),SDRS_GSM_Received_MO_FSM_Received_v2 numeric(15,3),SDRS_GSM_Received_MO_FSM_Received_v3 numeric(15,3),SDRS_GSM_Received_MO_FSM_Submit_Rcvd numeric(15,3),SDRS_GSM_Received_MO_FSM_Command_Rcvd numeric(15,3),SDRS_GSM_Received_MO_FSM_RS_Success numeric(15,3),SDRS_GSM_Received_MO_FSM_ES_Success numeric(15,3),SDRS_GSM_Received_ASC_Received_Total numeric(15,3),SDRS_GSM_Received_ASC_Received_v2 numeric(15,3),SDRS_GSM_Received_ASC_Received_v3 numeric(15,3),SDRS_GSM_Received_ASC_RS_Success numeric(15,3),SDRS_GSM_Received_ASC_ES_Success numeric(15,3),SDRS_GSM_Received_SRI_for_SM_Received numeric(15,3),SDRS_GSM_Received_SRI_for_SM_Resp_Success numeric(15,3),SDRS_GSM_Received_SRI_for_SM_Resp_Error numeric(15,3),SDRS_GSM_Received_MT_FSM_Received numeric(15,3),SDRS_GSM_Received_MT_FSM_Resp_Success numeric(15,3),SDRS_GSM_Received_MT_FSM_Resp_Error numeric(15,3),SDRS_GSM_Received_SMS_Deliv_Received numeric(15,3),SDRS_GSM_Received_SMS_Status_Rep_Received numeric(15,3),SDRS_IMS_MO_SIP_Received numeric(15,3),SDRS_IMS_MO_SIP_DecodeError numeric(15,3),SDRS_IMS_MO_SIP_MsgP2P numeric(15,3),SDRS_IMS_MO_SIP_RR_Success numeric(15,3),SDRS_IMS_MO_SIP_RR_Failure numeric(15,3),SDRS_IMS_MO_SIP_Sent numeric(15,3),SDRS_IMS_MO_SIP_Not_Sent numeric(15,3),SDRS_IMS_MO_SIP_Error_Returned numeric(15,3),SDRS_IMS_MO_SIP_Submit_Recvd numeric(15,3),SDRS_IMS_MO_SIP_RP_ACK_Recvd numeric(15,3),SDRS_IMS_MO_SIP_RP_ERROR_Recvd numeric(15,3),SDRS_IMS_MO_SIP_RP_SMMA_Recvd numeric(15,3),SDRS_IMS_MO_SIP_RP_ACK_Sent numeric(15,3),SDRS_IMS_MO_SIP_RP_ERROR_Sent numeric(15,3),SDRS_IMS_MO_PNR_Received numeric(15,3),SDRS_IMS_MO_PNA_NotSent numeric(15,3),SDRS_IMS_MO_Aux_17 numeric(15,3),SDRS_IMS_MO_Aux_18 numeric(15,3),SDRS_IMS_MO_Aux_19 numeric(15,3),SDRS_IMS_MO_Aux_20 numeric(15,3),SDRS_MME_Received_OFR_Submit_Received numeric(15,3),SDRS_MME_Received_OFR_Command_Received numeric(15,3),SDRS_MME_Received_OFR_Encoding_Error numeric(15,3),SDRS_MME_Received_OFR_Results_Sent numeric(15,3),SDRS_MME_Received_OFR_Error_Sent numeric(15,3),SDRS_MME_Received_ALR_Received numeric(15,3),SDRS_MME_Received_Aux_7 numeric(15,3),SDRS_MME_Received_Aux_8 numeric(15,3),SDRS_MME_Received_Aux_9 numeric(15,3),SDRS_MME_Received_Aux_10 numeric(15,3),SDRS_MME_Received_Aux_11 numeric(15,3),SDRS_MME_Received_Aux_12 numeric(15,3),SDRS_MME_Received_Aux_13 numeric(15,3),SDRS_MME_Received_Aux_14 numeric(15,3),SDRS_MME_Received_Aux_15 numeric(15,3),SDRS_MME_Received_Aux_16 numeric(15,3),SDRS_MME_Received_Aux_17 numeric(15,3),SDRS_MME_Received_Aux_18 numeric(15,3),SDRS_MME_Received_Aux_19 numeric(15,3),SDRS_MME_Received_Aux_20 numeric(15,3),SDRS_MO_Status_DPP_MO_Msg_Arrival numeric(15,3),SDRS_MO_Status_DPP_MO_CDMA_Received numeric(15,3),SDRS_MO_Status_DPP_MO_TDMA_Received numeric(15,3),SDRS_MO_Status_DPP_MO_RR_Sent numeric(15,3),SDRS_MO_Status_DPP_MO_RR_Not_Sent numeric(15,3),SDRS_MO_Status_DPP_MO_RE_Sent numeric(15,3),SDRS_MO_Status_DPP_MO_RE_Not_Sent numeric(15,3),SDRS_MO_Status_DPP_SMSNotify_Received numeric(15,3),SDRS_MO_Status_DPP_SMSNotify_RR_Success numeric(15,3),SDRS_MO_Status_DPP_SMSNotify_RR_NotSent numeric(15,3),SDRS_MO_Status_DPP_NotifyWithMDNRecvd numeric(15,3),SDRS_MO_Status_DPP_MO_CDMA_EMS_Rcvd numeric(15,3),SDRS_MO_Status_DPP_SMSNotify_RE_Success numeric(15,3),SDRS_MO_Status_DPP_SMSNotify_RE_NotSent numeric(15,3),SDRS_MO_Status_DPP_MO_Read_Ack_Rcvd numeric(15,3),SDRS_MO_Status_DPP_MO_From_Other_SMSC numeric(15,3),SDRS_MO_Status_DPP_Gen_Auto_Reply numeric(15,3),SDRS_MO_Status_DPP_MO_to_SMPP numeric(15,3),SDRS_MO_Status_DPP_MO_to_MT numeric(15,3),SDRS_MO_Status_DPP_MO_FDA_to_MDA numeric(15,3),SDRS_Msg_Delvrd_Hist_Total numeric(15,3),SDRS_Msg_Delvrd_Hist_Counter_1 numeric(15,3),SDRS_Msg_Delvrd_Hist_Counter_2 numeric(15,3),SDRS_Msg_Delvrd_Hist_Counter_3 numeric(15,3),SDRS_Msg_Delvrd_Hist_Counter_4 numeric(15,3),SDRS_Msg_Delvrd_Hist_Counter_5 numeric(15,3),SDRS_Msg_Delvrd_Hist_Counter_6 numeric(15,3),SDRS_Msg_Delvrd_Hist_Counter_7 numeric(15,3),SDRS_Msg_Delvrd_Hist_Counter_8 numeric(15,3),SDRS_Msg_Delvrd_Hist_Counter_9 numeric(15,3),SDRS_Msg_Delvrd_Hist_Aux_11 numeric(15,3),SDRS_Msg_Delvrd_Hist_Aux_12 numeric(15,3),SDRS_Msg_Delvrd_Hist_Aux_13 numeric(15,3),SDRS_Msg_Delvrd_Hist_Aux_14 numeric(15,3),SDRS_Msg_Delvrd_Hist_Aux_15 numeric(15,3),SDRS_Msg_Delvrd_Hist_Aux_16 numeric(15,3),SDRS_Msg_Delvrd_Hist_Aux_17 numeric(15,3),SDRS_Msg_Delvrd_Hist_Aux_18 numeric(15,3),SDRS_Msg_Delvrd_Hist_Aux_19 numeric(15,3),SDRS_Msg_Delvrd_Hist_Aux_20 numeric(15,3),SDRS_Msg_Not_Delvrd_Hist_Total numeric(15,3),SDRS_Msg_Not_Delvrd_Hist_Counter_1 numeric(15,3),SDRS_Msg_Not_Delvrd_Hist_Counter_2 numeric(15,3),SDRS_Msg_Not_Delvrd_Hist_Counter_3 numeric(15,3),SDRS_Msg_Not_Delvrd_Hist_Counter_4 numeric(15,3),SDRS_Msg_Not_Delvrd_Hist_Counter_5 numeric(15,3),SDRS_Msg_Not_Delvrd_Hist_Counter_6 numeric(15,3),SDRS_Msg_Not_Delvrd_Hist_Counter_7 numeric(15,3),SDRS_Msg_Not_Delvrd_Hist_Counter_8 numeric(15,3),SDRS_Msg_Not_Delvrd_Hist_Counter_9 numeric(15,3),SDRS_PPD_Diam_Failures_PPD_RC_3004 numeric(15,3),SDRS_PPD_Diam_Failures_PPD_RC_4010 numeric(15,3),SDRS_PPD_Diam_Failures_PPD_RC_4012 numeric(15,3),SDRS_PPD_Diam_Failures_PPD_RC_5003 numeric(15,3),SDRS_PPD_Diam_Failures_PPD_RC_5004 numeric(15,3),SDRS_PPD_Diam_Failures_PPD_RC_5005 numeric(15,3),SDRS_PPD_Diam_Failures_PPD_RC_5012 numeric(15,3),SDRS_PPD_Diam_Failures_PPD_RC_5030 numeric(15,3),SDRS_PPD_Diam_Failures_PPD_RC_5031 numeric(15,3),SDRS_PPD_Diam_Failures_Aux_10 numeric(15,3),SDRS_PPD_Diam_Failures_Aux_11 numeric(15,3),SDRS_PPD_Diam_Failures_Aux_12 numeric(15,3),SDRS_PPD_Diam_Failures_Aux_13 numeric(15,3),SDRS_PPD_Diam_Failures_Aux_14 numeric(15,3),SDRS_PPD_Diam_Failures_Aux_15 numeric(15,3),SDRS_PPD_Diam_Failures_PPD_InternalError numeric(15,3),SDRS_PPD_Diam_Failures_PPD_NoResponse numeric(15,3),SDRS_PPD_Diam_Failures_PPD_ProtocolError numeric(15,3),SDRS_PPD_Diam_Failures_PPD_PermanentFailure numeric(15,3),SDRS_PPD_Diam_Failures_PPD_UnknownError numeric(15,3),SDRS_Prepaid_Failures_PPD_AllocationLost numeric(15,3),SDRS_Prepaid_Failures_PPD_ServerBusy numeric(15,3),SDRS_Prepaid_Failures_PPD_ProtocolViolations numeric(15,3),SDRS_Prepaid_Failures_PPD_InvalidMissParameter numeric(15,3),SDRS_Prepaid_Failures_PPD_InvalidSubscrDetails numeric(15,3),SDRS_Prepaid_Failures_PPD_ECommerceDisabled numeric(15,3),SDRS_Prepaid_Failures_PPD_InvalidMerchantId numeric(15,3),SDRS_Prepaid_Failures_PPD_SubscriberActivityBarred numeric(15,3),SDRS_Prepaid_Failures_PPD_CallsInProgress numeric(15,3),SDRS_Prepaid_Failures_PPD_WrongTypeMissBalance numeric(15,3),SDRS_Prepaid_Failures_PPD_UnsubscribedService numeric(15,3),SDRS_Prepaid_Failures_PPD_InsufficientFunds numeric(15,3),SDRS_Prepaid_Failures_PPD_UnknownError numeric(15,3),SDRS_Prepaid_Failures_PPD_InternalError numeric(15,3),SDRS_Prepaid_Failures_UC_TOD_Denial numeric(15,3),SDRS_Prepaid_Failures_UC_Other_Denial numeric(15,3),SDRS_SDRS_Misc_QuarantineRqst numeric(15,3),SDRS_SDRS_Misc_QuarantineFail numeric(15,3),SDRS_SDRS_Misc_CloseReceived numeric(15,3),SDRS_SDRS_Misc_CloseSuccess numeric(15,3),SDRS_SDRS_Misc_Aux_5 numeric(15,3),SDRS_SDRS_Misc_Aux_6 numeric(15,3),SDRS_SDRS_Misc_Aux_7 numeric(15,3),SDRS_SDRS_Misc_Aux_8 numeric(15,3),SDRS_SDRS_Misc_Aux_9 numeric(15,3),SDRS_SDRS_Misc_Aux_10 numeric(15,3),SDRS_SDRS_Misc_Aux_11 numeric(15,3),SDRS_SDRS_Misc_Aux_12 numeric(15,3),SDRS_SDRS_Misc_Aux_13 numeric(15,3),SDRS_SDRS_Misc_Aux_14 numeric(15,3),SDRS_SDRS_Misc_Aux_15 numeric(15,3),SDRS_SDRS_Misc_Aux_16 numeric(15,3),SDRS_SDRS_Misc_Aux_17 numeric(15,3),SDRS_SDRS_Misc_Aux_18 numeric(15,3),SDRS_SDRS_Misc_Aux_19 numeric(15,3),SDRS_SDRS_Misc_Aux_20 numeric(15,3),SDRS_SMS_Gen_Op_Billing_record_commit numeric(15,3),SDRS_SMS_Gen_Op_Billing_record_failed numeric(15,3),SDRS_SMS_Gen_Op_Msg_Status_Table_Size numeric(15,3),SDRS_SMS_Gen_Op_Dlvry_Ack_created numeric(15,3),SDRS_SMS_Gen_Op_Msg_Overload_Rjct numeric(15,3),SDRS_SMS_Gen_Op_Msg_Status_Num_Inserts numeric(15,3),SDRS_SMS_Gen_Op_Msg_Status_Num_Deletes numeric(15,3),SDRS_SMS_Gen_Op_Green_Zone_Restrict numeric(15,3),SDRS_SMS_Gen_Op_Signature_Success numeric(15,3),SDRS_SMS_Gen_Op_Signature_Failure numeric(15,3),SDRS_SMS_Gen_Op_Banner_Success numeric(15,3),SDRS_SMS_Gen_Op_Banner_Failure numeric(15,3),SDRS_SMS_Gen_Op_DelAckSuppress numeric(15,3),SDRS_SMS_Gen_Op_LongMsgRelayTruncated numeric(15,3),SDRS_SMS_Gen_Op_SCPR_Rcvd numeric(15,3),SDRS_SMS_Gen_Op_Imsst_Received numeric(15,3),SDRS_SMS_Gen_Op_Imsst_Success numeric(15,3),SDRS_SMS_Gen_Op_InternalMsg_subType1 numeric(15,3),SDRS_SMS_Gen_Op_FDA_to_MDA numeric(15,3),SDRS_SMS_Gen_Op_Direct_to_MDA numeric(15,3),SDRS_SMS_Prepaid_Status_PPD_DebitRequest_Success numeric(15,3),SDRS_SMS_Prepaid_Status_PPD_DebitRequest_Failure numeric(15,3),SDRS_SMS_Prepaid_Status_PPD_QueryBalance_Success numeric(15,3),SDRS_SMS_Prepaid_Status_PPD_QueryBalance_Failure numeric(15,3),SDRS_SMS_Prepaid_Status_PPD_CreditRequest_Success numeric(15,3),SDRS_SMS_Prepaid_Status_PPD_CreditRequest_Failure numeric(15,3),SDRS_SMS_Prepaid_Status_PPD_Free_Messages numeric(15,3),SDRS_SMS_Prepaid_Status_RDB_Writes_Sent numeric(15,3),SDRS_SMS_Prepaid_Status_RDB_Write_Success numeric(15,3),SDRS_SMS_Prepaid_Status_RDB_Write_Errors numeric(15,3),SDRS_SMS_Prepaid_Status_RDB_Write_Failures numeric(15,3),SDRS_Validate_Msg_Status_IntervalShortMessage numeric(15,3),SDRS_Validate_Msg_Status_MessagesToSmpp numeric(15,3),SDRS_Validate_Msg_Status_MessagesToMsgMgr numeric(15,3),SDRS_Validate_Msg_Status_BliArrival numeric(15,3),SDRS_Validate_Msg_Status_InvalidServiceType numeric(15,3),SDRS_Validate_Msg_Status_InvalidSourceDN numeric(15,3),SDRS_Validate_Msg_Status_InvalidDestinationDN numeric(15,3),SDRS_Validate_Msg_Status_InvalidCOS numeric(15,3),SDRS_Validate_Msg_Status_OriginationDenied numeric(15,3),SDRS_Validate_Msg_Status_TerminationDenied numeric(15,3),SDRS_Validate_Msg_Status_RoutingFailed numeric(15,3),SDRS_Validate_Msg_Status_SystemError numeric(15,3),SDRS_Validate_Msg_Status_ClntNotInService numeric(15,3),SDRS_Validate_Msg_Status_Val_Sends numeric(15,3),SDRS_Validate_Msg_Status_Val_XP_Sends numeric(15,3),SDRS_Validate_Msg_Status_DeliveryReceipts numeric(15,3),SDRS_Validate_Msg_Status_SMSC_Loop_Detected numeric(15,3),SDRS_Validate_Msg_Status_CarbonCopies numeric(15,3),SDRS_Validate_Msg_Status_Forwards numeric(15,3),SDRS_Validate_Msg_Status_InternalMsg numeric(15,3),STAR_SMPP_Msg_Status_SMPP_MWI_Rcvd numeric(15,3),STAR_SMPP_Msg_Status_SMPP_Page_Rcvd numeric(15,3),STAR_SMPP_Msg_Status_SMPP_Pass_Rcvd numeric(15,3),STAR_SMPP_Msg_Status_SMPP_WAP_Rcvd numeric(15,3),STAR_SMPP_Msg_Status_SMPP_LBS_Rcvd numeric(15,3),STAR_SMPP_Msg_Status_SMPP_Query numeric(15,3),STAR_SMPP_Msg_Status_SMPP_Cancel numeric(15,3),STAR_SMPP_Msg_Status_SMPP_Replace numeric(15,3),STAR_SMPP_Msg_Status_SMPP_CellBrdcst_Rcvd numeric(15,3),STAR_SMPP_Msg_Status_SMPP_EMS_Rcvd numeric(15,3),STAR_SMPP_Msg_Status_WAP_Subtype_1 numeric(15,3),STAR_SMPP_Msg_Status_SCPD_Rcvd numeric(15,3),STAR_SMPP_Msg_Status_Msg_Overload_Rjct numeric(15,3),STAR_SMPP_Msg_Status_SMPP_to_ESME numeric(15,3),STAR_SMPP_Msg_Status_SMPP_Unsent_Full numeric(15,3),STAR_SMPP_Msg_Status_SMPP_Acks numeric(15,3),STAR_SMPP_Msg_Status_SMPP_Allocation_Lost numeric(15,3),STAR_SMPP_Msg_Status_SMPP_Bind_Failure numeric(15,3),STAR_SMPP_Msg_Status_SMPP_No_Enq_Ack numeric(15,3),STAR_SMPP_Msg_Status_SMPP_Packets_Dropped numeric(15,3));
